version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/catalogue"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/cart"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/user"
    schedule:
      interval: "daily"
  - package-ecosystem: "composer"
    directory: "/ratings/html"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/cart"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/catalogue"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/dispatch"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/front"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/load-gen"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/mongo"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/mysql"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/payment"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/ratings"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/shipping"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/user"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/shipping"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/payment"
    schedule:
      interval: "daily"
