apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user
  labels:
    service: {{ .Release.Name }}-user
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Release.Name }}-user
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-user
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: {{ .Release.Name }}
      {{ end }}
      containers:
      - name: {{ .Release.Name }}-user
        image: {{ .Values.image.repo }}/{{ .Values.image.prefix }}-user:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: INSTANA_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "$(INSTANA_AGENT_HOST):4317"
        - name: OTEL_SERVICE_NAME
          value: {{ .Release.Name }}-user
        - name: MONGO_URL
          value: 'mongodb://{{ .Release.Name }}-mongodb:27017/users'
        - name: REDIS_HOST
          value: {{ .Release.Name }}-redis
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
        readinessProbe:
          httpGet:
            path: /health-check
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 30
          successThreshold: 1
      restartPolicy: Always
