apiVersion: v2
type: application
name: otel-shop
version: 0.2.0
# [bump]
appVersion: 0.1.66
home: https://github.com/instana/otel-shop
description: Sample micoservices application - with OpenTelemetry
