apiVersion: v2
type: application
name: otel-shop
# [bump]
version: 0.1.166
appVersion: 0.1.67
home: https://github.com/instana/otel-shop
description: Sample micoservices application - with OpenTelemetry
